// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrueVote.Web.Repositories;

#nullable disable

namespace TrueVote.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240922152524_Creating VoteOptionDetails with relashionship with ReceivedVote")]
    partial class CreatingVoteOptionDetailswithrelashionshipwithReceivedVote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrueVote.Web.Entities.ReceivedVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OptionKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OptionKey");

                    b.ToTable("VoteOptions", (string)null);
                });

            modelBuilder.Entity("TrueVote.Web.Entities.VoteOptionDetails", b =>
                {
                    b.Property<int>("OptionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionKey"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OptionKey");

                    b.HasIndex("OptionKey");

                    b.ToTable("VoteOptionDetails", (string)null);
                });

            modelBuilder.Entity("TrueVote.Web.Entities.ReceivedVote", b =>
                {
                    b.HasOne("TrueVote.Web.Entities.VoteOptionDetails", "VoteOptionDetails")
                        .WithMany("ReceivedVotes")
                        .HasForeignKey("OptionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoteOptionDetails");
                });

            modelBuilder.Entity("TrueVote.Web.Entities.VoteOptionDetails", b =>
                {
                    b.Navigation("ReceivedVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
